baseurl: ''
exclude: ['README.md']
permalink: pretty
title: "Vishwakarma Software Solutions"

collections:
  services:
    output: true
    permalink: /Softwares/:path/
  team:
    output: true
    permalink: /Author/:path/
  testimonials:
    output: true
    permalink: /Projects/:path/


defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: UA-166601038-1

plugins:
  - jekyll-environment-variables
